Removed verification

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -40,15 +40,15 @@ vendor_lib() {
     fi
 
     # Verify extraction success
-    echo "-----> Verifying extraction success: $VENDOR_DIR/$LIBRARY-$VERSION"
-    if [ ! -d "$VENDOR_DIR/$LIBRARY-$VERSION" ]; then
-      echo " !     Failed to find extracted directory for $LIBRARY Version ($VERSION)"
-      exit 1
-    fi
+    # echo "-----> Verifying extraction success: $VENDOR_DIR/$LIBRARY-$VERSION"
+    # if [ ! -d "$VENDOR_DIR/$LIBRARY-$VERSION" ]; then
+    #   echo " !     Failed to find extracted directory for $LIBRARY Version ($VERSION)"
+    #   exit 1
+    # fi
 
     # Clean up downloaded archive
     rm "$VENDOR_DIR/$LIBRARY-$VERSION.tar.gz"
-    new end
+    # new end
 
     echo "-----> Successfully installed $LIBRARY-$VERSION"
 
